site_name: Git Package Management
docs_dir: core/components/gitpackagemanagement/docs
site_dir: _build/site
repo_url: https://github.com/TheBoxer/Git-Package-Management
nav:
- Home: index.md
- General:
  - Directory structure: directory-structure.md
  - Installation: installation.md
  - System settings: system-settings.md
  - Config:
    - General: config/general.md
    - Package: config/package.md
    - Database: config/database.md
    - Extension package: config/extension-package.md
    - Dependencies: config/dependencies.md
    - Build: config/build.md
    - Examples: config/examples.md
theme: readthedocs